SILAB BirdsEye
{
	ColBackground = {0.85, 0.85, 0.85, 1};
	VisAreaText = false;
	BirdsEye SCNX
	{
		PC_Size = 16;
		ColRoad = {1, 1, 1};
		ColBigRoad = {1, 0.75, 0.27};
		ColRoadBorder = {0.65, 0.65, 0.65};
		ColArea = {0.8, 0.75, 0.7, 0.2};
		FillArea = true;
		FillVisObjects = true;
		ColTreeObjects = { 0.7, 0.85, 0.65 };
		ColHouseObjects = { 0.8, 0.75, 0.7 };
		ColFieldObjects = { 0.85, 0.85, 0.7 };
		ColVisObjects = {0.8, 0.8, 0.8};
		ColLGVisObjects = {1, 0, 0};
	};
};