UsedRoadUserTable CountryTraffic
{
   # CountryWooded.inc:
   Object = CarVan;
   Object = WildBoar_slow;
   # CountryValley.inc:
   Object = CarVan;
   Object = Truck;
   Object = WildBoar_slow;
   Object = IvecoDaily_TrafficSafety_222_20;
   Object = MercedesSprinter_construction;
   Object = AudiA6;
   Object = MercedesC;
   Object = OpelInsignia;
   Object = VWGolf;
   Object = VWPassat;
   Object = RenaultTwingo;
   Object = MitsubishiASX;
   # CountryFarmed.inc:
   Object = BMW645; // Ueberholer im Sommer
   Object = PorscheMacan; // alternativ fuer Winter
   Object = Car;
   Object = FiatPanda;
   Object = CarVan;
   Object = Car;
   Object = ClaasAxion;
   Object = BMWR1200;
   Object = KTMRC125;
   Object = MercedesC_police;
   Object = MercedesSprinter_Ambulance;
   # CountryBridge.inc:
   Object = CarVan;
   Object = Car;
};
