UsedRoadUserTable Motorway
{
   # MotorwayWorks.inc, MotorwayMobileWorks.inc:
   Object = HyundaiVeloster;
   Object = VWBus_grau;
   Object = MercedesSprinter;
   Object = TruckMotorway;
   Object = IvecoDaily_TrafficSafety_222_20;
   Object = MercedesSprinter_construction;
   Object = IvecoDaily_Pickup;
   Object = TruckMotorway;
   Object = CarVan;
   Object = VanTruck;
   Object = Car;
   Object = TruckMotorway;
   Object = Car;
   Object = Car;
   # Motorway.inc:
   Object = MAN_TGL;
   Object = BMW645;
   Object = LiebherrLTM1055_crane;
   Object = MAN_TGX_Tanker;
   Object = MAN_TGX;
   Object = MercedesActros;
   Object = BMWR1200;
   Object = IvecoDaily_TowTruck;
   
   
   
   
   
   
};
